language: objective-c
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update
    - brew install ios-sim
cache:
  directories:
    - vendor/bundle
    - vendor/Pods
install:
    - bundle install --path=vendor/bundle
    - bundle exec rake pod:install --silent
script:
    - bundle exec rake spec