require 'rake'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = Dir.glob('*spec.rb')
  t.rspec_opts = '--format documentation --fail-fast'
  # t.rspec_opts << ' more options'
end
task :default => :spec